message( STATUS )
message( STATUS "------------------ General configuration for ${PROJECT_NAME} ")
message( STATUS )
message( STATUS "CMAKE_BINARY_DIR=              ${CMAKE_BINARY_DIR}")
message( STATUS "SYSTEM INFO =                  Arch: ${CMAKE_SYSTEM_PROCESSOR} ; System version: ${CMAKE_SYSTEM_VERSION}" )
message( STATUS "CMAKE Generator=               ${CMAKE_GENERATOR}")
message( STATUS "COMPILER INFO =                ID: ${CMAKE_CXX_COMPILER_ID} (${CMAKE_CXX_COMPILER}) ; version: ${CMAKE_CXX_COMPILER_VERSION}")
message( STATUS "CMAKE_BUILD_TYPE=              ${CMAKE_BUILD_TYPE}")
message( STATUS "CMAKE_C_FLAGS=                 ${CMAKE_C_FLAGS}")
message( STATUS "CMAKE_C_FLAGS_DEBUG=           ${CMAKE_C_FLAGS_DEBUG}")
message( STATUS "CMAKE_C_FLAGS_RELEASE=         ${CMAKE_C_FLAGS_RELEASE}")
message( STATUS "CMAKE_CXX_FLAGS=               ${CMAKE_CXX_FLAGS}")
message( STATUS "CMAKE_CXX_FLAGS_DEBUG=         ${CMAKE_CXX_FLAGS_DEBUG}")
message( STATUS "CMAKE_CXX_FLAGS_RELEASE=       ${CMAKE_CXX_FLAGS_RELEASE}")
message( STATUS "CMAKE_EXE_LINKER_FLAGS=        ${CMAKE_EXE_LINKER_FLAGS}")
message( STATUS "CMAKE_EXE_LINKER_FLAGS_DEBUG=  ${CMAKE_EXE_LINKER_FLAGS_DEBUG}")
message( STATUS "CMAKE_EXE_LINKER_FLAGS_RELEASE=${CMAKE_EXE_LINKER_FLAGS_RELEASE}")

message( STATUS )
message( STATUS "CMAKE_MODULE_PATH=             ${CMAKE_MODULE_PATH}" )
message( STATUS "CMAKE_INSTALL_PREFIX=          ${CMAKE_INSTALL_PREFIX}" )
message( STATUS "WARNINGS_ANSI_ISO=             ${WARNINGS_ANSI_ISO} \t WARNINGS_ARE_ERRORS= ${WARNINGS_ARE_ERRORS}" )
message( STATUS "PRODUCE_BETTER_EXES=           ${PRODUCE_BETTER_EXES}" )
message( STATUS )

message( STATUS "BUILD_TESTS=                   ${BUILD_TESTS}" )

message( STATUS )
message( STATUS "------------------- Documentation  ----------------------" )
message( STATUS )
message( STATUS "INSTALL_DOC=                   ${INSTALL_DOC}" )
message( STATUS "DOXY_COVERAGE=                 ${DOXY_COVERAGE}" )
message( STATUS "USE_LATEX=                     ${USE_LATEX}" )
message( STATUS "USE_DOT=                       ${USE_DOT}" )
message( STATUS "USE_CHM=                       ${USE_CHM}" )
message( STATUS "USE_MATHJAX=                   ${USE_MATHJAX}" )
message( STATUS )
message( STATUS "Change a value with= cmake -D<Variable>=<Value>" )
message( STATUS )
